//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkrCompare {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkrCompare.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnCancel1 {
            get {
                return ResourceManager.GetString("btnCancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnDel {
            get {
                return ResourceManager.GetString("btnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnDel1 {
            get {
                return ResourceManager.GetString("btnDel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불러오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnLoad {
            get {
                return ResourceManager.GetString("btnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   읽기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnLoad1 {
            get {
                return ResourceManager.GetString("btnLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnOK1 {
            get {
                return ResourceManager.GetString("btnOK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    파라미터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnParam {
            get {
                return ResourceManager.GetString("btnParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSave1 {
            get {
                return ResourceManager.GetString("btnSave1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSetting {
            get {
                return ResourceManager.GetString("btnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///    시스템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSystem {
            get {
                return ResourceManager.GetString("btnSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dgvMeterialModel {
            get {
                return ResourceManager.GetString("dgvMeterialModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dgvMeterialNo {
            get {
                return ResourceManager.GetString("dgvMeterialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterDgvDuration {
            get {
                return ResourceManager.GetString("filterDgvDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterDgvLine {
            get {
                return ResourceManager.GetString("filterDgvLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterDgvModel {
            get {
                return ResourceManager.GetString("filterDgvModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterDgvNo {
            get {
                return ResourceManager.GetString("filterDgvNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품종과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterDgvProdName {
            get {
                return ResourceManager.GetString("filterDgvProdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddDelCancel {
            get {
                return ResourceManager.GetString("formAddDelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddDelName {
            get {
                return ResourceManager.GetString("formAddDelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddDelOK {
            get {
                return ResourceManager.GetString("formAddDelOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddDelTitle {
            get {
                return ResourceManager.GetString("formAddDelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formLNCDCycle {
            get {
                return ResourceManager.GetString("formLNCDCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인 상태 확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formLNCDLineCheck {
            get {
                return ResourceManager.GetString("formLNCDLineCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formLNCDSetIP {
            get {
                return ResourceManager.GetString("formLNCDSetIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   심볼과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formLNCDSymbol {
            get {
                return ResourceManager.GetString("formLNCDSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인 정보 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formLNCDTitle {
            get {
                return ResourceManager.GetString("formLNCDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동기화 주기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formProdFilterSyncDuration {
            get {
                return ResourceManager.GetString("formProdFilterSyncDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품 필터 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formProdFilterTitle {
            get {
                return ResourceManager.GetString("formProdFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingCheckAll {
            get {
                return ResourceManager.GetString("formSettingCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대X과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvCompRangeMaxX {
            get {
                return ResourceManager.GetString("formSettingDgvCompRangeMaxX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대Y과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvCompRangeMaxY {
            get {
                return ResourceManager.GetString("formSettingDgvCompRangeMaxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소X과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvCompRangeMinX {
            get {
                return ResourceManager.GetString("formSettingDgvCompRangeMinX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소Y과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvCompRangeMinY {
            get {
                return ResourceManager.GetString("formSettingDgvCompRangeMinY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비율과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvCompRangeRate {
            get {
                return ResourceManager.GetString("formSettingDgvCompRangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvProcIdx1 {
            get {
                return ResourceManager.GetString("formSettingDgvProcIdx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvTitleNo {
            get {
                return ResourceManager.GetString("formSettingDgvTitleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   결점 크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvTitleSize {
            get {
                return ResourceManager.GetString("formSettingDgvTitleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비교 공정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingGroupCompProc {
            get {
                return ResourceManager.GetString("formSettingGroupCompProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 영역 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingGroupCompRange {
            get {
                return ResourceManager.GetString("formSettingGroupCompRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   맵 표시 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingGroupJudgeRange {
            get {
                return ResourceManager.GetString("formSettingGroupJudgeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingGroupProc {
            get {
                return ResourceManager.GetString("formSettingGroupProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기준 공정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingGroupRefer {
            get {
                return ResourceManager.GetString("formSettingGroupRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingTitle {
            get {
                return ResourceManager.GetString("formSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AI 결과 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingUseMNTTAN {
            get {
                return ResourceManager.GetString("formSettingUseMNTTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 주기(분)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formStatCheckSetDuration {
            get {
                return ResourceManager.GetString("formStatCheckSetDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인 상태 감시 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formStatCheckSetTitle {
            get {
                return ResourceManager.GetString("formStatCheckSetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSystemTitle {
            get {
                return ResourceManager.GetString("formSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 감시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LiveSearch {
            get {
                return ResourceManager.GetString("LiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마킹 오차 비교과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mainFormTitle {
            get {
                return ResourceManager.GetString("mainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기간 검색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PeridoSearch {
            get {
                return ResourceManager.GetString("PeridoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 감시 중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcLiveSearch {
            get {
                return ResourceManager.GetString("ProcLiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기간 설정 검색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcSearch {
            get {
                return ResourceManager.GetString("ProcSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcStop {
            get {
                return ResourceManager.GetString("ProcStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 감시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tabLive {
            get {
                return ResourceManager.GetString("tabLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기간 검색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tabSearch {
            get {
                return ResourceManager.GetString("tabSearch", resourceCulture);
            }
        }
    }
}
