//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkCompare {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkCompare.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   적용되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string applied1 {
            get {
                return ResourceManager.GetString("applied1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PARAM 적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string appliedParam {
            get {
                return ResourceManager.GetString("appliedParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///    추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnCancel1 {
            get {
                return ResourceManager.GetString("btnCancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnCopy {
            get {
                return ResourceManager.GetString("btnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnDel {
            get {
                return ResourceManager.GetString("btnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnDel1 {
            get {
                return ResourceManager.GetString("btnDel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불러오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnLoad {
            get {
                return ResourceManager.GetString("btnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   읽기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnLoad1 {
            get {
                return ResourceManager.GetString("btnLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnOK1 {
            get {
                return ResourceManager.GetString("btnOK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    파라미터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnParam {
            get {
                return ResourceManager.GetString("btnParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSave1 {
            get {
                return ResourceManager.GetString("btnSave1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSetting {
            get {
                return ResourceManager.GetString("btnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///    시스템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSystem {
            get {
                return ResourceManager.GetString("btnSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   status.txt 파일을 확인할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CanNotFindStatusTxtFile {
            get {
                return ResourceManager.GetString("CanNotFindStatusTxtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이력 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string clearHistory {
            get {
                return ResourceManager.GetString("clearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램을 종료하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string closeProgram {
            get {
                return ResourceManager.GetString("closeProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2개 이상의 CSV 파일을 비교하십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string compare2OrMore {
            get {
                return ResourceManager.GetString("compare2OrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비교 공정 이름과 기준 공정 이름이 동일합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string compLncdAndRefLncdIsSame {
            get {
                return ResourceManager.GetString("compLncdAndRefLncdIsSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조건 Lot 검색이 실행 중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConditionalLotSearchIsRunning {
            get {
                return ResourceManager.GetString("ConditionalLotSearchIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 처리 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dataProcessingComplete {
            get {
                return ResourceManager.GetString("dataProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB 연결 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DbConnError {
            get {
                return ResourceManager.GetString("DbConnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBConnFailed {
            get {
                return ResourceManager.GetString("DBConnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB 접속에 성공하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBConnIsSuccessed {
            get {
                return ResourceManager.GetString("DBConnIsSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터를 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deleteData1 {
            get {
                return ResourceManager.GetString("deleteData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 삭제하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string deleteData2 {
            get {
                return ResourceManager.GetString("deleteData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dgvMeterialModel {
            get {
                return ResourceManager.GetString("dgvMeterialModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dgvMeterialNo {
            get {
                return ResourceManager.GetString("dgvMeterialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 저장 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string doneSavingData {
            get {
                return ResourceManager.GetString("doneSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 주기에 대한 상수를 입력해주십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enterSearchInterval {
            get {
                return ResourceManager.GetString("enterSearchInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오차 발생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorOccurrence {
            get {
                return ResourceManager.GetString("ErrorOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string fileName {
            get {
                return ResourceManager.GetString("fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterDgvDuration {
            get {
                return ResourceManager.GetString("filterDgvDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterDgvLine {
            get {
                return ResourceManager.GetString("filterDgvLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterDgvModel {
            get {
                return ResourceManager.GetString("filterDgvModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterDgvNo {
            get {
                return ResourceManager.GetString("filterDgvNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품종과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterDgvProdName {
            get {
                return ResourceManager.GetString("filterDgvProdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필터 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string filterSet {
            get {
                return ResourceManager.GetString("filterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV 파일 비교 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string finishedComparingCSV {
            get {
                return ResourceManager.GetString("finishedComparingCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddDelCancel {
            get {
                return ResourceManager.GetString("formAddDelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddDelName {
            get {
                return ResourceManager.GetString("formAddDelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddDelOK {
            get {
                return ResourceManager.GetString("formAddDelOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddDelProcessAdd {
            get {
                return ResourceManager.GetString("formAddDelProcessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddDelTitle {
            get {
                return ResourceManager.GetString("formAddDelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   복사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddDelTitleCopy {
            get {
                return ResourceManager.GetString("formAddDelTitleCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름이 비어있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formAddEmptyProcessName {
            get {
                return ResourceManager.GetString("formAddEmptyProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [실시간 감시] 오차 발생 LOT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formErrorLotDispTitleLive {
            get {
                return ResourceManager.GetString("formErrorLotDispTitleLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [선택 검색] 오차 발생 LOT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formErrorLotDispTitleSearch {
            get {
                return ResourceManager.GetString("formErrorLotDispTitleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formLNCDCycle {
            get {
                return ResourceManager.GetString("formLNCDCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인 상태 확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formLNCDLineCheck {
            get {
                return ResourceManager.GetString("formLNCDLineCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   심볼과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formLNCDSymbol {
            get {
                return ResourceManager.GetString("formLNCDSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인 정보 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formLNCDTitle {
            get {
                return ResourceManager.GetString("formLNCDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동기화 주기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formProdFilterSyncDuration {
            get {
                return ResourceManager.GetString("formProdFilterSyncDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품 필터 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formProdFilterTitle {
            get {
                return ResourceManager.GetString("formProdFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingCheckAll {
            get {
                return ResourceManager.GetString("formSettingCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대X과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvCompRangeMaxX {
            get {
                return ResourceManager.GetString("formSettingDgvCompRangeMaxX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대Y과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvCompRangeMaxY {
            get {
                return ResourceManager.GetString("formSettingDgvCompRangeMaxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소X과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvCompRangeMinX {
            get {
                return ResourceManager.GetString("formSettingDgvCompRangeMinX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소Y과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvCompRangeMinY {
            get {
                return ResourceManager.GetString("formSettingDgvCompRangeMinY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비율과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvCompRangeRate {
            get {
                return ResourceManager.GetString("formSettingDgvCompRangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvProcIdx1 {
            get {
                return ResourceManager.GetString("formSettingDgvProcIdx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvTitleNo {
            get {
                return ResourceManager.GetString("formSettingDgvTitleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   결점 크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingDgvTitleSize {
            get {
                return ResourceManager.GetString("formSettingDgvTitleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비교 공정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingGroupCompProc {
            get {
                return ResourceManager.GetString("formSettingGroupCompProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 영역 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingGroupCompRange {
            get {
                return ResourceManager.GetString("formSettingGroupCompRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   맵 표시 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingGroupJudgeRange {
            get {
                return ResourceManager.GetString("formSettingGroupJudgeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingGroupProc {
            get {
                return ResourceManager.GetString("formSettingGroupProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기준 공정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingGroupRefer {
            get {
                return ResourceManager.GetString("formSettingGroupRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingModelApplyed {
            get {
                return ResourceManager.GetString("formSettingModelApplyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델을 선택하여 주십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingPlzSelectModel {
            get {
                return ResourceManager.GetString("formSettingPlzSelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingTitle {
            get {
                return ResourceManager.GetString("formSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AI 결과 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSettingUseMNTTAN {
            get {
                return ResourceManager.GetString("formSettingUseMNTTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 주기(분)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formStatCheckSetDuration {
            get {
                return ResourceManager.GetString("formStatCheckSetDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인 상태 감시 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formStatCheckSetTitle {
            get {
                return ResourceManager.GetString("formStatCheckSetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string formSystemTitle {
            get {
                return ResourceManager.GetString("formSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정보가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InformationDoesNotExist {
            get {
                return ResourceManager.GetString("InformationDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0~255 사이에 올바른 숫자를 입력해주십시오과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InsertCorrectNumber {
            get {
                return ResourceManager.GetString("InsertCorrectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 이름을 입력해주십시오과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InsertFileName {
            get {
                return ResourceManager.GetString("InsertFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP 주소가 잘못 입력되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IpAddressIsWrong {
            get {
                return ResourceManager.GetString("IpAddressIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LINE ID가 비어있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lineIdIsEmpty {
            get {
                return ResourceManager.GetString("lineIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 감시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LiveSearch {
            get {
                return ResourceManager.GetString("LiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LNCD가 비어있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lncdIsEmpty {
            get {
                return ResourceManager.GetString("lncdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터를 불러오겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string loadData1 {
            get {
                return ResourceManager.GetString("loadData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 불러오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string loadData2 {
            get {
                return ResourceManager.GetString("loadData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lot 요약(비교 결과)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lotSummaryCompResult {
            get {
                return ResourceManager.GetString("lotSummaryCompResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lot 요약 : Lot 요약 정보가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LotSummaryIsEmpty {
            get {
                return ResourceManager.GetString("LotSummaryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lot 요약(Lot 이름)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lotSummaryLotName {
            get {
                return ResourceManager.GetString("lotSummaryLotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lot 요약(세부 표시)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LotSummaryShowDetail {
            get {
                return ResourceManager.GetString("LotSummaryShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마킹 오차 비교과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mainFormTitle {
            get {
                return ResourceManager.GetString("mainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대 CSV 파일 갯수는 100개입니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string maximumCsvFiles {
            get {
                return ResourceManager.GetString("maximumCsvFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름에는 [ _ ] 를 포함할 수 없습니다. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NamesCannotContain {
            get {
                return ResourceManager.GetString("NamesCannotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비교 데이터 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoComparingData {
            get {
                return ResourceManager.GetString("NoComparingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   탐색할 필터 데이터가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string noFilterData {
            get {
                return ResourceManager.GetString("noFilterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line 정보가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoLineInformation {
            get {
                return ResourceManager.GetString("NoLineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lot 요약 정보가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoLotSummaryData {
            get {
                return ResourceManager.GetString("NoLotSummaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델 정보가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoModelInformation {
            get {
                return ResourceManager.GetString("NoModelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품종 정보가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoProductInformation {
            get {
                return ResourceManager.GetString("NoProductInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 행이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string noSelectedRow {
            get {
                return ResourceManager.GetString("noSelectedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기간 검색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PeridoSearch {
            get {
                return ResourceManager.GetString("PeridoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기간 선택 검색 작업이 완료되었습니다. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string periodOperationIsComplete {
            get {
                return ResourceManager.GetString("periodOperationIsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로세스를 선택하여주십시오과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string plzChooseProcess {
            get {
                return ResourceManager.GetString("plzChooseProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 처리 중....과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string processingData {
            get {
                return ResourceManager.GetString("processingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 감시 중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcLiveSearch {
            get {
                return ResourceManager.GetString("ProcLiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기간 설정 검색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcSearch {
            get {
                return ResourceManager.GetString("ProcSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcStop {
            get {
                return ResourceManager.GetString("ProcStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품종과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 검색이 실행 중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string realtimeExplorationInProgress {
            get {
                return ResourceManager.GetString("realtimeExplorationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 검식이 이미 정지되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RealtimeExplorationIsAlreadyStopped {
            get {
                return ResourceManager.GetString("RealtimeExplorationIsAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 검색이 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string realtimeSearchOperationIscomplete {
            get {
                return ResourceManager.GetString("realtimeSearchOperationIscomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동일한 이름의 Line ID가 존재합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string sameLineIdExsits {
            get {
                return ResourceManager.GetString("sameLineIdExsits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동일한 이름의 LNCD가 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string sameLNCDexists {
            get {
                return ResourceManager.GetString("sameLNCDexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 내용을 저장하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string saveCurrentData1 {
            get {
                return ResourceManager.GetString("saveCurrentData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 저장하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string saveCurrentData2 {
            get {
                return ResourceManager.GetString("saveCurrentData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 검색이 취소되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string searchingDataCancel {
            get {
                return ResourceManager.GetString("searchingDataCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 LOT을 불러왔습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectedLotIsLoaded {
            get {
                return ResourceManager.GetString("SelectedLotIsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택 탐색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectiveMonitoring {
            get {
                return ResourceManager.GetString("SelectiveMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV 비교 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string startComparingCSV {
            get {
                return ResourceManager.GetString("startComparingCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 검색 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string startRealtimeExploration {
            get {
                return ResourceManager.GetString("startRealtimeExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StatusCheck {
            get {
                return ResourceManager.GetString("StatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 감시 중지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StopRealtimeExploration {
            get {
                return ResourceManager.GetString("StopRealtimeExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실시간 감시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tabLive {
            get {
                return ResourceManager.GetString("tabLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기간 검색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tabSearch {
            get {
                return ResourceManager.GetString("tabSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   탐색 진행 중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string theSearingIsInProgress {
            get {
                return ResourceManager.GetString("theSearingIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경고과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
