//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefectDBManager {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DefectDBManager.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 결점정보를 적용하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplySelectedDefectInfos {
            get {
                return ResourceManager.GetString("ApplySelectedDefectInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   읽어오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnLoadtAreaDel {
            get {
                return ResourceManager.GetString("btnLoadtAreaDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSaveAreaDel {
            get {
                return ResourceManager.GetString("btnSaveAreaDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결됨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   접속과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBLoginConnect {
            get {
                return ResourceManager.GetString("DBLoginConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   접속 해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBLoginDisonnect {
            get {
                return ResourceManager.GetString("DBLoginDisonnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBLoginDomain {
            get {
                return ResourceManager.GetString("DBLoginDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   호스트 IP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBLoginHostIP {
            get {
                return ResourceManager.GetString("DBLoginHostIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBLoginID {
            get {
                return ResourceManager.GetString("DBLoginID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBLoginPort {
            get {
                return ResourceManager.GetString("DBLoginPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBLoginPW {
            get {
                return ResourceManager.GetString("DBLoginPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB 접속 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBLoginTitle {
            get {
                return ResourceManager.GetString("DBLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유형과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBLoginType {
            get {
                return ResourceManager.GetString("DBLoginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 베이스 진행 상태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DBProgressTitle {
            get {
                return ResourceManager.GetString("DBProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량 수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DefectEditorTitle {
            get {
                return ResourceManager.GetString("DefectEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DefectSkip_LNCD {
            get {
                return ResourceManager.GetString("DefectSkip_LNCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대 크기(mm)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DefectSkip_Max {
            get {
                return ResourceManager.GetString("DefectSkip_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소 크기(mm)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DefectSkip_Min {
            get {
                return ResourceManager.GetString("DefectSkip_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DefectSkip_Name {
            get {
                return ResourceManager.GetString("DefectSkip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정 별 불량 크기 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DefectSkipTitle {
            get {
                return ResourceManager.GetString("DefectSkipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   출하처과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결 끊김과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량 수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EditDefect {
            get {
                return ResourceManager.GetString("EditDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량 클레스 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EditDefectClass {
            get {
                return ResourceManager.GetString("EditDefectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량 수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EditDefectTitle {
            get {
                return ResourceManager.GetString("EditDefectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연신과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그외과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ETC {
            get {
                return ResourceManager.GetString("ETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV 파일 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExportCSV {
            get {
                return ResourceManager.GetString("ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일이 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검사 데이터 마스크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string gbInspDataMask {
            get {
                return ResourceManager.GetString("gbInspDataMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량 제외 크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string gbSizeSkip {
            get {
                return ResourceManager.GetString("gbSizeSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string judgeNG {
            get {
                return ResourceManager.GetString("judgeNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비교 데이터 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string judgeNoCompData {
            get {
                return ResourceManager.GetString("judgeNoCompData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string judgeNoData {
            get {
                return ResourceManager.GetString("judgeNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string judgeOK {
            get {
                return ResourceManager.GetString("judgeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M^2 불량수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listBCNO_3 {
            get {
                return ResourceManager.GetString("listBCNO_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원단 BCNO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listBCNO_5 {
            get {
                return ResourceManager.GetString("listBCNO_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   관리 NO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listFAULTDAT_1 {
            get {
                return ResourceManager.GetString("listFAULTDAT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량 CNT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listFAULTDAT_2 {
            get {
                return ResourceManager.GetString("listFAULTDAT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listFAULTDAT_6 {
            get {
                return ResourceManager.GetString("listFAULTDAT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listFAULTDAT_7 {
            get {
                return ResourceManager.GetString("listFAULTDAT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   관리NO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listINSPDAT_0 {
            get {
                return ResourceManager.GetString("listINSPDAT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품종과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listINSPDAT_1 {
            get {
                return ResourceManager.GetString("listINSPDAT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인코드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listMRKCTLMST_0 {
            get {
                return ResourceManager.GetString("listMRKCTLMST_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불량 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listMRKCTLMST_1 {
            get {
                return ResourceManager.GetString("listMRKCTLMST_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품종과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listMRKCTLMST_2 {
            get {
                return ResourceManager.GetString("listMRKCTLMST_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사이즈과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listMRKCTLMST_3 {
            get {
                return ResourceManager.GetString("listMRKCTLMST_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품종과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listPTRY0P_0 {
            get {
                return ResourceManager.GetString("listPTRY0P_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연신 Lot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listPTRY0P_1 {
            get {
                return ResourceManager.GetString("listPTRY0P_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인코드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listPTRY0P_2 {
            get {
                return ResourceManager.GetString("listPTRY0P_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개시 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listPTRY0P_3 {
            get {
                return ResourceManager.GetString("listPTRY0P_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listPTRY0P_4 {
            get {
                return ResourceManager.GetString("listPTRY0P_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원단 Lot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listPTRYLP_0 {
            get {
                return ResourceManager.GetString("listPTRYLP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   점착 Lot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listPTRYLP_1 {
            get {
                return ResourceManager.GetString("listPTRYLP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품종과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listPTRYLP_5 {
            get {
                return ResourceManager.GetString("listPTRYLP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lot 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listTodayPTLY0P_0 {
            get {
                return ResourceManager.GetString("listTodayPTLY0P_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listTodayPTLY0P_1 {
            get {
                return ResourceManager.GetString("listTodayPTLY0P_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LNCD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listTodayPTLY0P_2 {
            get {
                return ResourceManager.GetString("listTodayPTLY0P_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개시 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listTodayPTLY0P_3 {
            get {
                return ResourceManager.GetString("listTodayPTLY0P_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string listTodayPTLY0P_4 {
            get {
                return ResourceManager.GetString("listTodayPTLY0P_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   점착 Lot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LotName {
            get {
                return ResourceManager.GetString("LotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   마킹 그룹과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MarkingGroup {
            get {
                return ResourceManager.GetString("MarkingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NextFaultPage {
            get {
                return ResourceManager.GetString("NextFaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV 파일 열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenCSV {
            get {
                return ResourceManager.GetString("OpenCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   옵션과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lot 번호를 입력하세요!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseInsertLotNumber {
            get {
                return ResourceManager.GetString("PleaseInsertLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   숫자를 입력해주십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseInsertNumbers {
            get {
                return ResourceManager.GetString("PleaseInsertNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10자리의 Lot 번호를 입력하세요!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseInsertTenDigitsOfLotNumber {
            get {
                return ResourceManager.GetString("PleaseInsertTenDigitsOfLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   먼저 DB에 접속해주십시요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseLoginToTheDB {
            get {
                return ResourceManager.GetString("PleaseLoginToTheDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이전과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PrevFaultPage {
            get {
                return ResourceManager.GetString("PrevFaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV 데이터 검색중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProgramIsSearchingCSV {
            get {
                return ResourceManager.GetString("ProgramIsSearchingCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB 데이터 검색중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProgramIsSearchingDB {
            get {
                return ResourceManager.GetString("ProgramIsSearchingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터를 초기화 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetAllData {
            get {
                return ResourceManager.GetString("ResetAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchEndTime {
            get {
                return ResourceManager.GetString("SearchEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchStartTime {
            get {
                return ResourceManager.GetString("SearchStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 CSV형식이 없습니다.Dest.ini파일을 확인하시길 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectedCSVFormatTypeDoesNotExist {
            get {
                return ResourceManager.GetString("SelectedCSVFormatTypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 시간 설청과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetSearchTime {
            get {
                return ResourceManager.GetString("SetSearchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기타 데이터 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킵 파라미터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ShowSkipParam {
            get {
                return ResourceManager.GetString("ShowSkipParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SizeX과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SizeX {
            get {
                return ResourceManager.GetString("SizeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SizeY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SizeY {
            get {
                return ResourceManager.GetString("SizeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경계 반사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SkipParam1 {
            get {
                return ResourceManager.GetString("SkipParam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정투과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SkipParam2 {
            get {
                return ResourceManager.GetString("SkipParam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주기성 뷸량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SkipParam3 {
            get {
                return ResourceManager.GetString("SkipParam3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   크로스 불량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SkipParam4 {
            get {
                return ResourceManager.GetString("SkipParam4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정반사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SkipParam5 {
            get {
                return ResourceManager.GetString("SkipParam5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미분 반사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SkipParam6 {
            get {
                return ResourceManager.GetString("SkipParam6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TG {
            get {
                return ResourceManager.GetString("TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   결점 정보가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ThereAreNoDefectInfs {
            get {
                return ResourceManager.GetString("ThereAreNoDefectInfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당하는 출하처의 정보가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ThereIsNoDestinationInfomation {
            get {
                return ResourceManager.GetString("ThereIsNoDestinationInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정보 갱신과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 갱신과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateData {
            get {
                return ResourceManager.GetString("UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검사 데이터 마스크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UseMask {
            get {
                return ResourceManager.GetString("UseMask", resourceCulture);
            }
        }
    }
}
