//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefectDBManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DefectDBManager.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 추가.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 적용.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택된 결점정보를 적용하시겠습니까?.
        /// </summary>
        internal static string ApplySelectedDefectInfos {
            get {
                return ResourceManager.GetString("ApplySelectedDefectInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 읽어오기.
        /// </summary>
        internal static string btnLoadtAreaDel {
            get {
                return ResourceManager.GetString("btnLoadtAreaDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 저장.
        /// </summary>
        internal static string btnSaveAreaDel {
            get {
                return ResourceManager.GetString("btnSaveAreaDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체 삭제.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연결됨.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연결.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 접속.
        /// </summary>
        internal static string DBLoginConnect {
            get {
                return ResourceManager.GetString("DBLoginConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 접속 해제.
        /// </summary>
        internal static string DBLoginDisonnect {
            get {
                return ResourceManager.GetString("DBLoginDisonnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Name.
        /// </summary>
        internal static string DBLoginDomain {
            get {
                return ResourceManager.GetString("DBLoginDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 호스트 IP.
        /// </summary>
        internal static string DBLoginHostIP {
            get {
                return ResourceManager.GetString("DBLoginHostIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디.
        /// </summary>
        internal static string DBLoginID {
            get {
                return ResourceManager.GetString("DBLoginID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 포트.
        /// </summary>
        internal static string DBLoginPort {
            get {
                return ResourceManager.GetString("DBLoginPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호.
        /// </summary>
        internal static string DBLoginPW {
            get {
                return ResourceManager.GetString("DBLoginPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB 접속 정보.
        /// </summary>
        internal static string DBLoginTitle {
            get {
                return ResourceManager.GetString("DBLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유형.
        /// </summary>
        internal static string DBLoginType {
            get {
                return ResourceManager.GetString("DBLoginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터 베이스 진행 상태.
        /// </summary>
        internal static string DBProgressTitle {
            get {
                return ResourceManager.GetString("DBProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불량 수정.
        /// </summary>
        internal static string DefectEditorTitle {
            get {
                return ResourceManager.GetString("DefectEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공정 이름.
        /// </summary>
        internal static string DefectSkip_LNCD {
            get {
                return ResourceManager.GetString("DefectSkip_LNCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최대 크기(mm).
        /// </summary>
        internal static string DefectSkip_Max {
            get {
                return ResourceManager.GetString("DefectSkip_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최소 크기(mm).
        /// </summary>
        internal static string DefectSkip_Min {
            get {
                return ResourceManager.GetString("DefectSkip_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이름.
        /// </summary>
        internal static string DefectSkip_Name {
            get {
                return ResourceManager.GetString("DefectSkip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공정 별 불량 크기 설정.
        /// </summary>
        internal static string DefectSkipTitle {
            get {
                return ResourceManager.GetString("DefectSkipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제.
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 출하처.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연결 끊김.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불량 수정.
        /// </summary>
        internal static string EditDefect {
            get {
                return ResourceManager.GetString("EditDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불량 클레스 변경.
        /// </summary>
        internal static string EditDefectClass {
            get {
                return ResourceManager.GetString("EditDefectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불량 수정.
        /// </summary>
        internal static string EditDefectTitle {
            get {
                return ResourceManager.GetString("EditDefectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연신.
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 그외.
        /// </summary>
        internal static string ETC {
            get {
                return ResourceManager.GetString("ETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV 파일 저장.
        /// </summary>
        internal static string ExportCSV {
            get {
                return ResourceManager.GetString("ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일이 존재하지 않습니다..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검사 데이터 마스크.
        /// </summary>
        internal static string gbInspDataMask {
            get {
                return ResourceManager.GetString("gbInspDataMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불량 제외 크기.
        /// </summary>
        internal static string gbSizeSkip {
            get {
                return ResourceManager.GetString("gbSizeSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M^2 불량수.
        /// </summary>
        internal static string listBCNO_3 {
            get {
                return ResourceManager.GetString("listBCNO_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 원단 BCNO.
        /// </summary>
        internal static string listBCNO_5 {
            get {
                return ResourceManager.GetString("listBCNO_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 관리 NO.
        /// </summary>
        internal static string listFAULTDAT_1 {
            get {
                return ResourceManager.GetString("listFAULTDAT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불량 CNT.
        /// </summary>
        internal static string listFAULTDAT_2 {
            get {
                return ResourceManager.GetString("listFAULTDAT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 종류.
        /// </summary>
        internal static string listFAULTDAT_6 {
            get {
                return ResourceManager.GetString("listFAULTDAT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불량번호.
        /// </summary>
        internal static string listFAULTDAT_7 {
            get {
                return ResourceManager.GetString("listFAULTDAT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 관리NO.
        /// </summary>
        internal static string listINSPDAT_0 {
            get {
                return ResourceManager.GetString("listINSPDAT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 품종.
        /// </summary>
        internal static string listINSPDAT_1 {
            get {
                return ResourceManager.GetString("listINSPDAT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 라인코드.
        /// </summary>
        internal static string listMRKCTLMST_0 {
            get {
                return ResourceManager.GetString("listMRKCTLMST_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불량 ID.
        /// </summary>
        internal static string listMRKCTLMST_1 {
            get {
                return ResourceManager.GetString("listMRKCTLMST_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 품종.
        /// </summary>
        internal static string listMRKCTLMST_2 {
            get {
                return ResourceManager.GetString("listMRKCTLMST_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사이즈.
        /// </summary>
        internal static string listMRKCTLMST_3 {
            get {
                return ResourceManager.GetString("listMRKCTLMST_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 품종.
        /// </summary>
        internal static string listPTRY0P_0 {
            get {
                return ResourceManager.GetString("listPTRY0P_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연신 Lot.
        /// </summary>
        internal static string listPTRY0P_1 {
            get {
                return ResourceManager.GetString("listPTRY0P_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 라인코드.
        /// </summary>
        internal static string listPTRY0P_2 {
            get {
                return ResourceManager.GetString("listPTRY0P_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개시 시간.
        /// </summary>
        internal static string listPTRY0P_3 {
            get {
                return ResourceManager.GetString("listPTRY0P_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 종료 시간.
        /// </summary>
        internal static string listPTRY0P_4 {
            get {
                return ResourceManager.GetString("listPTRY0P_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 원단 Lot.
        /// </summary>
        internal static string listPTRYLP_0 {
            get {
                return ResourceManager.GetString("listPTRYLP_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 점착 Lot.
        /// </summary>
        internal static string listPTRYLP_1 {
            get {
                return ResourceManager.GetString("listPTRYLP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 품종.
        /// </summary>
        internal static string listPTRYLP_5 {
            get {
                return ResourceManager.GetString("listPTRYLP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot 정보.
        /// </summary>
        internal static string listTodayPTLY0P_0 {
            get {
                return ResourceManager.GetString("listTodayPTLY0P_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공정.
        /// </summary>
        internal static string listTodayPTLY0P_1 {
            get {
                return ResourceManager.GetString("listTodayPTLY0P_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LNCD.
        /// </summary>
        internal static string listTodayPTLY0P_2 {
            get {
                return ResourceManager.GetString("listTodayPTLY0P_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개시 시간.
        /// </summary>
        internal static string listTodayPTLY0P_3 {
            get {
                return ResourceManager.GetString("listTodayPTLY0P_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 종료 시간.
        /// </summary>
        internal static string listTodayPTLY0P_4 {
            get {
                return ResourceManager.GetString("listTodayPTLY0P_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 점착 Lot.
        /// </summary>
        internal static string LotName {
            get {
                return ResourceManager.GetString("LotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마킹 그룹.
        /// </summary>
        internal static string MarkingGroup {
            get {
                return ResourceManager.GetString("MarkingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max..
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min..
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다음.
        /// </summary>
        internal static string NextFaultPage {
            get {
                return ResourceManager.GetString("NextFaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV 파일 열기.
        /// </summary>
        internal static string OpenCSV {
            get {
                return ResourceManager.GetString("OpenCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 옵션.
        /// </summary>
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot 번호를 입력하세요!.
        /// </summary>
        internal static string PleaseInsertLotNumber {
            get {
                return ResourceManager.GetString("PleaseInsertLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 숫자를 입력해주십시요..
        /// </summary>
        internal static string PleaseInsertNumbers {
            get {
                return ResourceManager.GetString("PleaseInsertNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10자리의 Lot 번호를 입력하세요!.
        /// </summary>
        internal static string PleaseInsertTenDigitsOfLotNumber {
            get {
                return ResourceManager.GetString("PleaseInsertTenDigitsOfLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 먼저 DB에 접속해주십시요..
        /// </summary>
        internal static string PleaseLoginToTheDB {
            get {
                return ResourceManager.GetString("PleaseLoginToTheDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이전.
        /// </summary>
        internal static string PrevFaultPage {
            get {
                return ResourceManager.GetString("PrevFaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV 데이터 검색중입니다..
        /// </summary>
        internal static string ProgramIsSearchingCSV {
            get {
                return ResourceManager.GetString("ProgramIsSearchingCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB 데이터 검색중입니다..
        /// </summary>
        internal static string ProgramIsSearchingDB {
            get {
                return ResourceManager.GetString("ProgramIsSearchingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 초기화.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터를 초기화 하시겠습니까?.
        /// </summary>
        internal static string ResetAllData {
            get {
                return ResourceManager.GetString("ResetAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 종료 시간.
        /// </summary>
        internal static string SearchEndTime {
            get {
                return ResourceManager.GetString("SearchEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시작 시간.
        /// </summary>
        internal static string SearchStartTime {
            get {
                return ResourceManager.GetString("SearchStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택된 CSV형식이 없습니다.Dest.ini파일을 확인하시길 바랍니다..
        /// </summary>
        internal static string SelectedCSVFormatTypeDoesNotExist {
            get {
                return ResourceManager.GetString("SelectedCSVFormatTypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색 시간 설청.
        /// </summary>
        internal static string SetSearchTime {
            get {
                return ResourceManager.GetString("SetSearchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기타 데이터 표시.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스킵 파라미터.
        /// </summary>
        internal static string ShowSkipParam {
            get {
                return ResourceManager.GetString("ShowSkipParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeX.
        /// </summary>
        internal static string SizeX {
            get {
                return ResourceManager.GetString("SizeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeY.
        /// </summary>
        internal static string SizeY {
            get {
                return ResourceManager.GetString("SizeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 경계 반사.
        /// </summary>
        internal static string SkipParam1 {
            get {
                return ResourceManager.GetString("SkipParam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정투과.
        /// </summary>
        internal static string SkipParam2 {
            get {
                return ResourceManager.GetString("SkipParam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주기성 뷸량.
        /// </summary>
        internal static string SkipParam3 {
            get {
                return ResourceManager.GetString("SkipParam3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 크로스 불량.
        /// </summary>
        internal static string SkipParam4 {
            get {
                return ResourceManager.GetString("SkipParam4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정반사.
        /// </summary>
        internal static string SkipParam5 {
            get {
                return ResourceManager.GetString("SkipParam5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 미분 반사.
        /// </summary>
        internal static string SkipParam6 {
            get {
                return ResourceManager.GetString("SkipParam6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 도공.
        /// </summary>
        internal static string TG {
            get {
                return ResourceManager.GetString("TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 결점 정보가 존재하지 않습니다..
        /// </summary>
        internal static string ThereAreNoDefectInfs {
            get {
                return ResourceManager.GetString("ThereAreNoDefectInfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 해당하는 출하처의 정보가 존재하지 않습니다..
        /// </summary>
        internal static string ThereIsNoDestinationInfomation {
            get {
                return ResourceManager.GetString("ThereIsNoDestinationInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정보 갱신.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터 갱신.
        /// </summary>
        internal static string UpdateData {
            get {
                return ResourceManager.GetString("UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검사 데이터 마스크.
        /// </summary>
        internal static string UseMask {
            get {
                return ResourceManager.GetString("UseMask", resourceCulture);
            }
        }
    }
}
